# Generated by Django 4.2.1 on 2023-05-29 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('make', models.CharField(max_length=250)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023)])),
            ],
        ),
    ]
